version: '2.1'
services:
  mysql:
    build: ./mysql 
    container_name: mysql
    environment:
############  user,password and database name for wordpress ##############
##################  change them thorught .env file   #####################
      - WPDB=${WORDPRESS_DATABASE}
      - WPUSER=${WORDPRESS_USER}
      - WPPASS=${WORDPRESS_PASSWORD}
  
  downloader:
    build: ./downloader
    container_name: downloader 
    volumes:
      - /var/www/app
  
  app1:
    build: ./phpfpm
    image: phpfpm
    container_name: app1 
    environment:
############  user,password and database name for wordpress ##############
##################  change them thorught .env file   #####################
      - DB_ENV_WPDB=${WORDPRESS_DATABASE}
      - DB_ENV_WPUSER=${WORDPRESS_USER}
      - DB_ENV_WPPASS=${WORDPRESS_PASSWORD}
    links: 
      - mysql:db
    volumes_from:
      - downloader
  
  app2:
    image: phpfpm
    container_name: app2 
    environment:
############  user,password and database name for wordpress ##############
##################  change them thorught .env file   #####################
      - DB_ENV_WPDB="${WORDPRESS_DATABASE}"
      - DB_ENV_WPUSER="${WORDPRESS_USER}"
      - DB_ENV_WPPASS="${WORDPRESS_PASSWORD}"
    links: 
      - mysql:db
    volumes_from:
      - downloader

  nginx:
    build: ./nginx
    container_name: nginx 
    volumes_from: 
      - downloader
    links:
      - app1:app1
      - app2:app2
    ports:
      - "80:80"
  
