version: '2.1'
services:
  mysql:
    build: ./mysql 
    container_name: mysql
    environment:
############  user,password and database name for wordpress ##############
############  if you are planning to cahnge it make sure to change it at both of app1 and app2 ##########
      - WPDB=wordpress
      - WPUSER=wpuser
      - WPPASS=th1s1sp@ssw0rd 
  
  downloader:
    build: ./downloader
    container_name: downloader 
    volumes:
      - /var/www/app
  
  app1:
    build: ./phpfpm
    image: phpfpm
    container_name: app1 
    environment:
############  user,password and database name for wordpress ##############
      - DB_ENV_WPDB=wordpress
      - DB_ENV_WPUSER=wpuser
      - DB_ENV_WPPASS=th1s1sp@ssw0rd 
    links: 
      - mysql:db
    volumes_from:
      - downloader
  
  app2:
    image: phpfpm
    container_name: app2 
    environment:
############  user,password and database name for wordpress ##############
      - DB_ENV_WPDB=wordpress
      - DB_ENV_WPUSER=wpuser
      - DB_ENV_WPPASS=th1s1sp@ssw0rd 
    links: 
      - mysql:db
    volumes_from:
      - downloader

  nginx:
    build: ./nginx
    container_name: nginx 
    volumes_from: 
      - downloader
    links:
      - app1:app1
      - app2:app2
    ports:
      - "80:80"
  
